// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package models

import (
	"context"

	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolCallingChatModel creates a new instance of MockToolCallingChatModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolCallingChatModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolCallingChatModel {
	mock := &MockToolCallingChatModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolCallingChatModel is an autogenerated mock type for the ToolCallingChatModel type
type MockToolCallingChatModel struct {
	mock.Mock
}

type MockToolCallingChatModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolCallingChatModel) EXPECT() *MockToolCallingChatModel_Expecter {
	return &MockToolCallingChatModel_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockToolCallingChatModel
func (_mock *MockToolCallingChatModel) Generate(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.Message, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 *schema.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*schema.Message, ...model.Option) (*schema.Message, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*schema.Message, ...model.Option) *schema.Message); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*schema.Message, ...model.Option) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolCallingChatModel_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockToolCallingChatModel_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - input []*schema.Message
//   - opts ...model.Option
func (_e *MockToolCallingChatModel_Expecter) Generate(ctx interface{}, input interface{}, opts ...interface{}) *MockToolCallingChatModel_Generate_Call {
	return &MockToolCallingChatModel_Generate_Call{Call: _e.mock.On("Generate",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *MockToolCallingChatModel_Generate_Call) Run(run func(ctx context.Context, input []*schema.Message, opts ...model.Option)) *MockToolCallingChatModel_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*schema.Message
		if args[1] != nil {
			arg1 = args[1].([]*schema.Message)
		}
		var arg2 []model.Option
		var variadicArgs []model.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]model.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockToolCallingChatModel_Generate_Call) Return(message *schema.Message, err error) *MockToolCallingChatModel_Generate_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockToolCallingChatModel_Generate_Call) RunAndReturn(run func(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.Message, error)) *MockToolCallingChatModel_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function for the type MockToolCallingChatModel
func (_mock *MockToolCallingChatModel) Stream(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.StreamReader[*schema.Message], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 *schema.StreamReader[*schema.Message]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*schema.Message, ...model.Option) (*schema.StreamReader[*schema.Message], error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*schema.Message, ...model.Option) *schema.StreamReader[*schema.Message]); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.StreamReader[*schema.Message])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*schema.Message, ...model.Option) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolCallingChatModel_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockToolCallingChatModel_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - input []*schema.Message
//   - opts ...model.Option
func (_e *MockToolCallingChatModel_Expecter) Stream(ctx interface{}, input interface{}, opts ...interface{}) *MockToolCallingChatModel_Stream_Call {
	return &MockToolCallingChatModel_Stream_Call{Call: _e.mock.On("Stream",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *MockToolCallingChatModel_Stream_Call) Run(run func(ctx context.Context, input []*schema.Message, opts ...model.Option)) *MockToolCallingChatModel_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*schema.Message
		if args[1] != nil {
			arg1 = args[1].([]*schema.Message)
		}
		var arg2 []model.Option
		var variadicArgs []model.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]model.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockToolCallingChatModel_Stream_Call) Return(streamReader *schema.StreamReader[*schema.Message], err error) *MockToolCallingChatModel_Stream_Call {
	_c.Call.Return(streamReader, err)
	return _c
}

func (_c *MockToolCallingChatModel_Stream_Call) RunAndReturn(run func(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.StreamReader[*schema.Message], error)) *MockToolCallingChatModel_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// WithTools provides a mock function for the type MockToolCallingChatModel
func (_mock *MockToolCallingChatModel) WithTools(tools []*schema.ToolInfo) (model.ToolCallingChatModel, error) {
	ret := _mock.Called(tools)

	if len(ret) == 0 {
		panic("no return value specified for WithTools")
	}

	var r0 model.ToolCallingChatModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]*schema.ToolInfo) (model.ToolCallingChatModel, error)); ok {
		return returnFunc(tools)
	}
	if returnFunc, ok := ret.Get(0).(func([]*schema.ToolInfo) model.ToolCallingChatModel); ok {
		r0 = returnFunc(tools)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.ToolCallingChatModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*schema.ToolInfo) error); ok {
		r1 = returnFunc(tools)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolCallingChatModel_WithTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTools'
type MockToolCallingChatModel_WithTools_Call struct {
	*mock.Call
}

// WithTools is a helper method to define mock.On call
//   - tools []*schema.ToolInfo
func (_e *MockToolCallingChatModel_Expecter) WithTools(tools interface{}) *MockToolCallingChatModel_WithTools_Call {
	return &MockToolCallingChatModel_WithTools_Call{Call: _e.mock.On("WithTools", tools)}
}

func (_c *MockToolCallingChatModel_WithTools_Call) Run(run func(tools []*schema.ToolInfo)) *MockToolCallingChatModel_WithTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*schema.ToolInfo
		if args[0] != nil {
			arg0 = args[0].([]*schema.ToolInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockToolCallingChatModel_WithTools_Call) Return(toolCallingChatModel model.ToolCallingChatModel, err error) *MockToolCallingChatModel_WithTools_Call {
	_c.Call.Return(toolCallingChatModel, err)
	return _c
}

func (_c *MockToolCallingChatModel_WithTools_Call) RunAndReturn(run func(tools []*schema.ToolInfo) (model.ToolCallingChatModel, error)) *MockToolCallingChatModel_WithTools_Call {
	_c.Call.Return(run)
	return _c
}
