// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/internal/core/domain/repositories"
	"github.com/oniharnantyo/eino-notebook/pkg/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockArtifactRepository creates a new instance of MockArtifactRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtifactRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtifactRepository {
	mock := &MockArtifactRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArtifactRepository is an autogenerated mock type for the ArtifactRepository type
type MockArtifactRepository struct {
	mock.Mock
}

type MockArtifactRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtifactRepository) EXPECT() *MockArtifactRepository_Expecter {
	return &MockArtifactRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) Create(ctx context.Context, artifact *entities.Artifact) error {
	ret := _mock.Called(ctx, artifact)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Artifact) error); ok {
		r0 = returnFunc(ctx, artifact)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtifactRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArtifactRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - artifact *entities.Artifact
func (_e *MockArtifactRepository_Expecter) Create(ctx interface{}, artifact interface{}) *MockArtifactRepository_Create_Call {
	return &MockArtifactRepository_Create_Call{Call: _e.mock.On("Create", ctx, artifact)}
}

func (_c *MockArtifactRepository_Create_Call) Run(run func(ctx context.Context, artifact *entities.Artifact)) *MockArtifactRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Artifact
		if args[1] != nil {
			arg1 = args[1].(*entities.Artifact)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_Create_Call) Return(err error) *MockArtifactRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtifactRepository_Create_Call) RunAndReturn(run func(ctx context.Context, artifact *entities.Artifact) error) *MockArtifactRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtifactRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockArtifactRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockArtifactRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockArtifactRepository_Delete_Call {
	return &MockArtifactRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockArtifactRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockArtifactRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_Delete_Call) Return(err error) *MockArtifactRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtifactRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockArtifactRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Artifact, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Artifact, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Artifact); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockArtifactRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockArtifactRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockArtifactRepository_GetByID_Call {
	return &MockArtifactRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockArtifactRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockArtifactRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_GetByID_Call) Return(artifact *entities.Artifact, err error) *MockArtifactRepository_GetByID_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockArtifactRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Artifact, error)) *MockArtifactRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNotebookID provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) GetByNotebookID(ctx context.Context, notebookID uuid.UUID) ([]*entities.Artifact, error) {
	ret := _mock.Called(ctx, notebookID)

	if len(ret) == 0 {
		panic("no return value specified for GetByNotebookID")
	}

	var r0 []*entities.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.Artifact, error)); ok {
		return returnFunc(ctx, notebookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.Artifact); ok {
		r0 = returnFunc(ctx, notebookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, notebookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRepository_GetByNotebookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNotebookID'
type MockArtifactRepository_GetByNotebookID_Call struct {
	*mock.Call
}

// GetByNotebookID is a helper method to define mock.On call
//   - ctx context.Context
//   - notebookID uuid.UUID
func (_e *MockArtifactRepository_Expecter) GetByNotebookID(ctx interface{}, notebookID interface{}) *MockArtifactRepository_GetByNotebookID_Call {
	return &MockArtifactRepository_GetByNotebookID_Call{Call: _e.mock.On("GetByNotebookID", ctx, notebookID)}
}

func (_c *MockArtifactRepository_GetByNotebookID_Call) Run(run func(ctx context.Context, notebookID uuid.UUID)) *MockArtifactRepository_GetByNotebookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_GetByNotebookID_Call) Return(artifacts []*entities.Artifact, err error) *MockArtifactRepository_GetByNotebookID_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockArtifactRepository_GetByNotebookID_Call) RunAndReturn(run func(ctx context.Context, notebookID uuid.UUID) ([]*entities.Artifact, error)) *MockArtifactRepository_GetByNotebookID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNotebookIDAndStatus provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) GetByNotebookIDAndStatus(ctx context.Context, notebookID uuid.UUID, status entities.ArtifactStatus) ([]*entities.Artifact, error) {
	ret := _mock.Called(ctx, notebookID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByNotebookIDAndStatus")
	}

	var r0 []*entities.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entities.ArtifactStatus) ([]*entities.Artifact, error)); ok {
		return returnFunc(ctx, notebookID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entities.ArtifactStatus) []*entities.Artifact); ok {
		r0 = returnFunc(ctx, notebookID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, entities.ArtifactStatus) error); ok {
		r1 = returnFunc(ctx, notebookID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRepository_GetByNotebookIDAndStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNotebookIDAndStatus'
type MockArtifactRepository_GetByNotebookIDAndStatus_Call struct {
	*mock.Call
}

// GetByNotebookIDAndStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - notebookID uuid.UUID
//   - status entities.ArtifactStatus
func (_e *MockArtifactRepository_Expecter) GetByNotebookIDAndStatus(ctx interface{}, notebookID interface{}, status interface{}) *MockArtifactRepository_GetByNotebookIDAndStatus_Call {
	return &MockArtifactRepository_GetByNotebookIDAndStatus_Call{Call: _e.mock.On("GetByNotebookIDAndStatus", ctx, notebookID, status)}
}

func (_c *MockArtifactRepository_GetByNotebookIDAndStatus_Call) Run(run func(ctx context.Context, notebookID uuid.UUID, status entities.ArtifactStatus)) *MockArtifactRepository_GetByNotebookIDAndStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 entities.ArtifactStatus
		if args[2] != nil {
			arg2 = args[2].(entities.ArtifactStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_GetByNotebookIDAndStatus_Call) Return(artifacts []*entities.Artifact, err error) *MockArtifactRepository_GetByNotebookIDAndStatus_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockArtifactRepository_GetByNotebookIDAndStatus_Call) RunAndReturn(run func(ctx context.Context, notebookID uuid.UUID, status entities.ArtifactStatus) ([]*entities.Artifact, error)) *MockArtifactRepository_GetByNotebookIDAndStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNotebookIDAndType provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) GetByNotebookIDAndType(ctx context.Context, notebookID uuid.UUID, artifactType entities.ArtifactType) ([]*entities.Artifact, error) {
	ret := _mock.Called(ctx, notebookID, artifactType)

	if len(ret) == 0 {
		panic("no return value specified for GetByNotebookIDAndType")
	}

	var r0 []*entities.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entities.ArtifactType) ([]*entities.Artifact, error)); ok {
		return returnFunc(ctx, notebookID, artifactType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entities.ArtifactType) []*entities.Artifact); ok {
		r0 = returnFunc(ctx, notebookID, artifactType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, entities.ArtifactType) error); ok {
		r1 = returnFunc(ctx, notebookID, artifactType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactRepository_GetByNotebookIDAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNotebookIDAndType'
type MockArtifactRepository_GetByNotebookIDAndType_Call struct {
	*mock.Call
}

// GetByNotebookIDAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - notebookID uuid.UUID
//   - artifactType entities.ArtifactType
func (_e *MockArtifactRepository_Expecter) GetByNotebookIDAndType(ctx interface{}, notebookID interface{}, artifactType interface{}) *MockArtifactRepository_GetByNotebookIDAndType_Call {
	return &MockArtifactRepository_GetByNotebookIDAndType_Call{Call: _e.mock.On("GetByNotebookIDAndType", ctx, notebookID, artifactType)}
}

func (_c *MockArtifactRepository_GetByNotebookIDAndType_Call) Run(run func(ctx context.Context, notebookID uuid.UUID, artifactType entities.ArtifactType)) *MockArtifactRepository_GetByNotebookIDAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 entities.ArtifactType
		if args[2] != nil {
			arg2 = args[2].(entities.ArtifactType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_GetByNotebookIDAndType_Call) Return(artifacts []*entities.Artifact, err error) *MockArtifactRepository_GetByNotebookIDAndType_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockArtifactRepository_GetByNotebookIDAndType_Call) RunAndReturn(run func(ctx context.Context, notebookID uuid.UUID, artifactType entities.ArtifactType) ([]*entities.Artifact, error)) *MockArtifactRepository_GetByNotebookIDAndType_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) List(ctx context.Context, filter repositories.ArtifactFilter) ([]*entities.Artifact, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Artifact
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.ArtifactFilter) ([]*entities.Artifact, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.ArtifactFilter) []*entities.Artifact); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.ArtifactFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, repositories.ArtifactFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockArtifactRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockArtifactRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repositories.ArtifactFilter
func (_e *MockArtifactRepository_Expecter) List(ctx interface{}, filter interface{}) *MockArtifactRepository_List_Call {
	return &MockArtifactRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockArtifactRepository_List_Call) Run(run func(ctx context.Context, filter repositories.ArtifactFilter)) *MockArtifactRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.ArtifactFilter
		if args[1] != nil {
			arg1 = args[1].(repositories.ArtifactFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_List_Call) Return(artifacts []*entities.Artifact, n int, err error) *MockArtifactRepository_List_Call {
	_c.Call.Return(artifacts, n, err)
	return _c
}

func (_c *MockArtifactRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter repositories.ArtifactFilter) ([]*entities.Artifact, int, error)) *MockArtifactRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockArtifactRepository
func (_mock *MockArtifactRepository) Update(ctx context.Context, artifact *entities.Artifact) error {
	ret := _mock.Called(ctx, artifact)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Artifact) error); ok {
		r0 = returnFunc(ctx, artifact)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtifactRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockArtifactRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - artifact *entities.Artifact
func (_e *MockArtifactRepository_Expecter) Update(ctx interface{}, artifact interface{}) *MockArtifactRepository_Update_Call {
	return &MockArtifactRepository_Update_Call{Call: _e.mock.On("Update", ctx, artifact)}
}

func (_c *MockArtifactRepository_Update_Call) Run(run func(ctx context.Context, artifact *entities.Artifact)) *MockArtifactRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Artifact
		if args[1] != nil {
			arg1 = args[1].(*entities.Artifact)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtifactRepository_Update_Call) Return(err error) *MockArtifactRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtifactRepository_Update_Call) RunAndReturn(run func(ctx context.Context, artifact *entities.Artifact) error) *MockArtifactRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
