// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/internal/core/domain/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConversationRepository creates a new instance of MockConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationRepository {
	mock := &MockConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationRepository is an autogenerated mock type for the ConversationRepository type
type MockConversationRepository struct {
	mock.Mock
}

type MockConversationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationRepository) EXPECT() *MockConversationRepository_Expecter {
	return &MockConversationRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) Delete(ctx context.Context, responseID string) error {
	ret := _mock.Called(ctx, responseID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, responseID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConversationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - responseID string
func (_e *MockConversationRepository_Expecter) Delete(ctx interface{}, responseID interface{}) *MockConversationRepository_Delete_Call {
	return &MockConversationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, responseID)}
}

func (_c *MockConversationRepository_Delete_Call) Run(run func(ctx context.Context, responseID string)) *MockConversationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_Delete_Call) Return(err error) *MockConversationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, responseID string) error) *MockConversationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) Exists(ctx context.Context, responseID string) (bool, error) {
	ret := _mock.Called(ctx, responseID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, responseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, responseID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, responseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockConversationRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - responseID string
func (_e *MockConversationRepository_Expecter) Exists(ctx interface{}, responseID interface{}) *MockConversationRepository_Exists_Call {
	return &MockConversationRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, responseID)}
}

func (_c *MockConversationRepository_Exists_Call) Run(run func(ctx context.Context, responseID string)) *MockConversationRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_Exists_Call) Return(b bool, err error) *MockConversationRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockConversationRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, responseID string) (bool, error)) *MockConversationRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResponseID provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) FindByResponseID(ctx context.Context, responseID string) (*entities.Conversation, error) {
	ret := _mock.Called(ctx, responseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByResponseID")
	}

	var r0 *entities.Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Conversation, error)); ok {
		return returnFunc(ctx, responseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Conversation); ok {
		r0 = returnFunc(ctx, responseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, responseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_FindByResponseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResponseID'
type MockConversationRepository_FindByResponseID_Call struct {
	*mock.Call
}

// FindByResponseID is a helper method to define mock.On call
//   - ctx context.Context
//   - responseID string
func (_e *MockConversationRepository_Expecter) FindByResponseID(ctx interface{}, responseID interface{}) *MockConversationRepository_FindByResponseID_Call {
	return &MockConversationRepository_FindByResponseID_Call{Call: _e.mock.On("FindByResponseID", ctx, responseID)}
}

func (_c *MockConversationRepository_FindByResponseID_Call) Run(run func(ctx context.Context, responseID string)) *MockConversationRepository_FindByResponseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_FindByResponseID_Call) Return(conversation *entities.Conversation, err error) *MockConversationRepository_FindByResponseID_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockConversationRepository_FindByResponseID_Call) RunAndReturn(run func(ctx context.Context, responseID string) (*entities.Conversation, error)) *MockConversationRepository_FindByResponseID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) FindByID(ctx context.Context, id string) (*entities.Conversation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Conversation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Conversation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockConversationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConversationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockConversationRepository_FindByID_Call {
	return &MockConversationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockConversationRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockConversationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_FindByID_Call) Return(conversation *entities.Conversation, err error) *MockConversationRepository_FindByID_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockConversationRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entities.Conversation, error)) *MockConversationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestConversationID provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) GetLatestConversationID(ctx context.Context, notebookID string) (string, error) {
	ret := _mock.Called(ctx, notebookID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestConversationID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, notebookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, notebookID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, notebookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_GetLatestConversationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestConversationID'
type MockConversationRepository_GetLatestConversationID_Call struct {
	*mock.Call
}

// GetLatestConversationID is a helper method to define mock.On call
//   - ctx context.Context
//   - notebookID string
func (_e *MockConversationRepository_Expecter) GetLatestConversationID(ctx interface{}, notebookID interface{}) *MockConversationRepository_GetLatestConversationID_Call {
	return &MockConversationRepository_GetLatestConversationID_Call{Call: _e.mock.On("GetLatestConversationID", ctx, notebookID)}
}

func (_c *MockConversationRepository_GetLatestConversationID_Call) Run(run func(ctx context.Context, notebookID string)) *MockConversationRepository_GetLatestConversationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_GetLatestConversationID_Call) Return(s string, err error) *MockConversationRepository_GetLatestConversationID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConversationRepository_GetLatestConversationID_Call) RunAndReturn(run func(ctx context.Context, notebookID string) (string, error)) *MockConversationRepository_GetLatestConversationID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) GetMessages(ctx context.Context, conversationID string, limit int, beforeSequence *int, isConversationHistory *bool) ([]*entities.Message, error) {
	ret := _mock.Called(ctx, conversationID, limit, beforeSequence, isConversationHistory)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*entities.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int, *bool) ([]*entities.Message, error)); ok {
		return returnFunc(ctx, conversationID, limit, beforeSequence, isConversationHistory)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int, *bool) []*entities.Message); ok {
		r0 = returnFunc(ctx, conversationID, limit, beforeSequence, isConversationHistory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, *int, *bool) error); ok {
		r1 = returnFunc(ctx, conversationID, limit, beforeSequence, isConversationHistory)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockConversationRepository_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID string
//   - limit int
//   - beforeSequence *int
//   - isConversationHistory *bool
func (_e *MockConversationRepository_Expecter) GetMessages(ctx interface{}, conversationID interface{}, limit interface{}, beforeSequence interface{}, isConversationHistory interface{}) *MockConversationRepository_GetMessages_Call {
	return &MockConversationRepository_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, conversationID, limit, beforeSequence, isConversationHistory)}
}

func (_c *MockConversationRepository_GetMessages_Call) Run(run func(ctx context.Context, conversationID string, limit int, beforeSequence *int, isConversationHistory *bool)) *MockConversationRepository_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 *bool
		if args[4] != nil {
			arg4 = args[4].(*bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockConversationRepository_GetMessages_Call) Return(messages []*entities.Message, err error) *MockConversationRepository_GetMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockConversationRepository_GetMessages_Call) RunAndReturn(run func(ctx context.Context, conversationID string, limit int, beforeSequence *int, isConversationHistory *bool) ([]*entities.Message, error)) *MockConversationRepository_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) List(ctx context.Context, filter repositories.ConversationFilter) ([]*entities.Conversation, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Conversation
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.ConversationFilter) ([]*entities.Conversation, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.ConversationFilter) []*entities.Conversation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.ConversationFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, repositories.ConversationFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConversationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockConversationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repositories.ConversationFilter
func (_e *MockConversationRepository_Expecter) List(ctx interface{}, filter interface{}) *MockConversationRepository_List_Call {
	return &MockConversationRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockConversationRepository_List_Call) Run(run func(ctx context.Context, filter repositories.ConversationFilter)) *MockConversationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.ConversationFilter
		if args[1] != nil {
			arg1 = args[1].(repositories.ConversationFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_List_Call) Return(conversations []*entities.Conversation, n int, err error) *MockConversationRepository_List_Call {
	_c.Call.Return(conversations, n, err)
	return _c
}

func (_c *MockConversationRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter repositories.ConversationFilter) ([]*entities.Conversation, int, error)) *MockConversationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) Save(ctx context.Context, conversation *entities.Conversation, messages []*entities.Message) error {
	ret := _mock.Called(ctx, conversation, messages)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Conversation, []*entities.Message) error); ok {
		r0 = returnFunc(ctx, conversation, messages)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockConversationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - conversation *entities.Conversation
//   - messages []*entities.Message
func (_e *MockConversationRepository_Expecter) Save(ctx interface{}, conversation interface{}, messages interface{}) *MockConversationRepository_Save_Call {
	return &MockConversationRepository_Save_Call{Call: _e.mock.On("Save", ctx, conversation, messages)}
}

func (_c *MockConversationRepository_Save_Call) Run(run func(ctx context.Context, conversation *entities.Conversation, messages []*entities.Message)) *MockConversationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Conversation
		if args[1] != nil {
			arg1 = args[1].(*entities.Conversation)
		}
		var arg2 []*entities.Message
		if args[2] != nil {
			arg2 = args[2].([]*entities.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationRepository_Save_Call) Return(err error) *MockConversationRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, conversation *entities.Conversation, messages []*entities.Message) error) *MockConversationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
