// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/internal/core/domain/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConversationRepository creates a new instance of MockConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationRepository {
	mock := &MockConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationRepository is an autogenerated mock type for the ConversationRepository type
type MockConversationRepository struct {
	mock.Mock
}

type MockConversationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationRepository) EXPECT() *MockConversationRepository_Expecter {
	return &MockConversationRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) Delete(ctx context.Context, responseID string) error {
	ret := _mock.Called(ctx, responseID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, responseID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConversationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - responseID string
func (_e *MockConversationRepository_Expecter) Delete(ctx interface{}, responseID interface{}) *MockConversationRepository_Delete_Call {
	return &MockConversationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, responseID)}
}

func (_c *MockConversationRepository_Delete_Call) Run(run func(ctx context.Context, responseID string)) *MockConversationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_Delete_Call) Return(err error) *MockConversationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, responseID string) error) *MockConversationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) Exists(ctx context.Context, responseID string) (bool, error) {
	ret := _mock.Called(ctx, responseID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, responseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, responseID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, responseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockConversationRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - responseID string
func (_e *MockConversationRepository_Expecter) Exists(ctx interface{}, responseID interface{}) *MockConversationRepository_Exists_Call {
	return &MockConversationRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, responseID)}
}

func (_c *MockConversationRepository_Exists_Call) Run(run func(ctx context.Context, responseID string)) *MockConversationRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_Exists_Call) Return(b bool, err error) *MockConversationRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockConversationRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, responseID string) (bool, error)) *MockConversationRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResponseID provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) FindByResponseID(ctx context.Context, responseID string) (*entities.Conversation, error) {
	ret := _mock.Called(ctx, responseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByResponseID")
	}

	var r0 *entities.Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Conversation, error)); ok {
		return returnFunc(ctx, responseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Conversation); ok {
		r0 = returnFunc(ctx, responseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, responseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_FindByResponseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResponseID'
type MockConversationRepository_FindByResponseID_Call struct {
	*mock.Call
}

// FindByResponseID is a helper method to define mock.On call
//   - ctx context.Context
//   - responseID string
func (_e *MockConversationRepository_Expecter) FindByResponseID(ctx interface{}, responseID interface{}) *MockConversationRepository_FindByResponseID_Call {
	return &MockConversationRepository_FindByResponseID_Call{Call: _e.mock.On("FindByResponseID", ctx, responseID)}
}

func (_c *MockConversationRepository_FindByResponseID_Call) Run(run func(ctx context.Context, responseID string)) *MockConversationRepository_FindByResponseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_FindByResponseID_Call) Return(conversation *entities.Conversation, err error) *MockConversationRepository_FindByResponseID_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockConversationRepository_FindByResponseID_Call) RunAndReturn(run func(ctx context.Context, responseID string) (*entities.Conversation, error)) *MockConversationRepository_FindByResponseID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) List(ctx context.Context, filter repositories.ConversationFilter) ([]*entities.Conversation, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Conversation
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.ConversationFilter) ([]*entities.Conversation, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.ConversationFilter) []*entities.Conversation); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.ConversationFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, repositories.ConversationFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConversationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockConversationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repositories.ConversationFilter
func (_e *MockConversationRepository_Expecter) List(ctx interface{}, filter interface{}) *MockConversationRepository_List_Call {
	return &MockConversationRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockConversationRepository_List_Call) Run(run func(ctx context.Context, filter repositories.ConversationFilter)) *MockConversationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.ConversationFilter
		if args[1] != nil {
			arg1 = args[1].(repositories.ConversationFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_List_Call) Return(conversations []*entities.Conversation, n int, err error) *MockConversationRepository_List_Call {
	_c.Call.Return(conversations, n, err)
	return _c
}

func (_c *MockConversationRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter repositories.ConversationFilter) ([]*entities.Conversation, int, error)) *MockConversationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) Save(ctx context.Context, conversation *entities.Conversation) error {
	ret := _mock.Called(ctx, conversation)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Conversation) error); ok {
		r0 = returnFunc(ctx, conversation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockConversationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - conversation *entities.Conversation
func (_e *MockConversationRepository_Expecter) Save(ctx interface{}, conversation interface{}) *MockConversationRepository_Save_Call {
	return &MockConversationRepository_Save_Call{Call: _e.mock.On("Save", ctx, conversation)}
}

func (_c *MockConversationRepository_Save_Call) Run(run func(ctx context.Context, conversation *entities.Conversation)) *MockConversationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Conversation
		if args[1] != nil {
			arg1 = args[1].(*entities.Conversation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_Save_Call) Return(err error) *MockConversationRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, conversation *entities.Conversation) error) *MockConversationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
