// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/pkg/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageRepository creates a new instance of MockImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageRepository {
	mock := &MockImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageRepository is an autogenerated mock type for the ImageRepository type
type MockImageRepository struct {
	mock.Mock
}

type MockImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageRepository) EXPECT() *MockImageRepository_Expecter {
	return &MockImageRepository_Expecter{mock: &_m.Mock}
}

// CountBySourceID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) CountBySourceID(ctx context.Context, sourceID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for CountBySourceID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, sourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, sourceID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_CountBySourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBySourceID'
type MockImageRepository_CountBySourceID_Call struct {
	*mock.Call
}

// CountBySourceID is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID uuid.UUID
func (_e *MockImageRepository_Expecter) CountBySourceID(ctx interface{}, sourceID interface{}) *MockImageRepository_CountBySourceID_Call {
	return &MockImageRepository_CountBySourceID_Call{Call: _e.mock.On("CountBySourceID", ctx, sourceID)}
}

func (_c *MockImageRepository_CountBySourceID_Call) Run(run func(ctx context.Context, sourceID uuid.UUID)) *MockImageRepository_CountBySourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_CountBySourceID_Call) Return(n int, err error) *MockImageRepository_CountBySourceID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageRepository_CountBySourceID_Call) RunAndReturn(run func(ctx context.Context, sourceID uuid.UUID) (int, error)) *MockImageRepository_CountBySourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockImageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockImageRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockImageRepository_Delete_Call {
	return &MockImageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockImageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockImageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Delete_Call) Return(err error) *MockImageRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockImageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySourceID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) DeleteBySourceID(ctx context.Context, sourceID uuid.UUID) error {
	ret := _mock.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySourceID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sourceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_DeleteBySourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySourceID'
type MockImageRepository_DeleteBySourceID_Call struct {
	*mock.Call
}

// DeleteBySourceID is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID uuid.UUID
func (_e *MockImageRepository_Expecter) DeleteBySourceID(ctx interface{}, sourceID interface{}) *MockImageRepository_DeleteBySourceID_Call {
	return &MockImageRepository_DeleteBySourceID_Call{Call: _e.mock.On("DeleteBySourceID", ctx, sourceID)}
}

func (_c *MockImageRepository_DeleteBySourceID_Call) Run(run func(ctx context.Context, sourceID uuid.UUID)) *MockImageRepository_DeleteBySourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_DeleteBySourceID_Call) Return(err error) *MockImageRepository_DeleteBySourceID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_DeleteBySourceID_Call) RunAndReturn(run func(ctx context.Context, sourceID uuid.UUID) error) *MockImageRepository_DeleteBySourceID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.Image, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Image, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Image); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockImageRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockImageRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockImageRepository_FindByID_Call {
	return &MockImageRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockImageRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockImageRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_FindByID_Call) Return(image *entities.Image, err error) *MockImageRepository_FindByID_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Image, error)) *MockImageRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySourceID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) FindBySourceID(ctx context.Context, sourceID uuid.UUID) ([]*entities.Image, error) {
	ret := _mock.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySourceID")
	}

	var r0 []*entities.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.Image, error)); ok {
		return returnFunc(ctx, sourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.Image); ok {
		r0 = returnFunc(ctx, sourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_FindBySourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySourceID'
type MockImageRepository_FindBySourceID_Call struct {
	*mock.Call
}

// FindBySourceID is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID uuid.UUID
func (_e *MockImageRepository_Expecter) FindBySourceID(ctx interface{}, sourceID interface{}) *MockImageRepository_FindBySourceID_Call {
	return &MockImageRepository_FindBySourceID_Call{Call: _e.mock.On("FindBySourceID", ctx, sourceID)}
}

func (_c *MockImageRepository_FindBySourceID_Call) Run(run func(ctx context.Context, sourceID uuid.UUID)) *MockImageRepository_FindBySourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_FindBySourceID_Call) Return(images []*entities.Image, err error) *MockImageRepository_FindBySourceID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageRepository_FindBySourceID_Call) RunAndReturn(run func(ctx context.Context, sourceID uuid.UUID) ([]*entities.Image, error)) *MockImageRepository_FindBySourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Save(ctx context.Context, image *entities.Image) error {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Image) error); ok {
		r0 = returnFunc(ctx, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockImageRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - image *entities.Image
func (_e *MockImageRepository_Expecter) Save(ctx interface{}, image interface{}) *MockImageRepository_Save_Call {
	return &MockImageRepository_Save_Call{Call: _e.mock.On("Save", ctx, image)}
}

func (_c *MockImageRepository_Save_Call) Run(run func(ctx context.Context, image *entities.Image)) *MockImageRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Image
		if args[1] != nil {
			arg1 = args[1].(*entities.Image)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Save_Call) Return(err error) *MockImageRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_Save_Call) RunAndReturn(run func(ctx context.Context, image *entities.Image) error) *MockImageRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
