// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/pkg/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKnowledgeRepository creates a new instance of MockKnowledgeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKnowledgeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKnowledgeRepository {
	mock := &MockKnowledgeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKnowledgeRepository is an autogenerated mock type for the KnowledgeRepository type
type MockKnowledgeRepository struct {
	mock.Mock
}

type MockKnowledgeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKnowledgeRepository) EXPECT() *MockKnowledgeRepository_Expecter {
	return &MockKnowledgeRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockKnowledgeRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKnowledgeRepository_Expecter) Count(ctx interface{}) *MockKnowledgeRepository_Count_Call {
	return &MockKnowledgeRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockKnowledgeRepository_Count_Call) Run(run func(ctx context.Context)) *MockKnowledgeRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_Count_Call) Return(n int64, err error) *MockKnowledgeRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockKnowledgeRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockKnowledgeRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountBySourceID provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) CountBySourceID(ctx context.Context, sourceID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for CountBySourceID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, sourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, sourceID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeRepository_CountBySourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBySourceID'
type MockKnowledgeRepository_CountBySourceID_Call struct {
	*mock.Call
}

// CountBySourceID is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID uuid.UUID
func (_e *MockKnowledgeRepository_Expecter) CountBySourceID(ctx interface{}, sourceID interface{}) *MockKnowledgeRepository_CountBySourceID_Call {
	return &MockKnowledgeRepository_CountBySourceID_Call{Call: _e.mock.On("CountBySourceID", ctx, sourceID)}
}

func (_c *MockKnowledgeRepository_CountBySourceID_Call) Run(run func(ctx context.Context, sourceID uuid.UUID)) *MockKnowledgeRepository_CountBySourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_CountBySourceID_Call) Return(n int, err error) *MockKnowledgeRepository_CountBySourceID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockKnowledgeRepository_CountBySourceID_Call) RunAndReturn(run func(ctx context.Context, sourceID uuid.UUID) (int, error)) *MockKnowledgeRepository_CountBySourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKnowledgeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKnowledgeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKnowledgeRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockKnowledgeRepository_Delete_Call {
	return &MockKnowledgeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockKnowledgeRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKnowledgeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_Delete_Call) Return(err error) *MockKnowledgeRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKnowledgeRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockKnowledgeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySourceID provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) DeleteBySourceID(ctx context.Context, sourceID uuid.UUID) error {
	ret := _mock.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySourceID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sourceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKnowledgeRepository_DeleteBySourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySourceID'
type MockKnowledgeRepository_DeleteBySourceID_Call struct {
	*mock.Call
}

// DeleteBySourceID is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID uuid.UUID
func (_e *MockKnowledgeRepository_Expecter) DeleteBySourceID(ctx interface{}, sourceID interface{}) *MockKnowledgeRepository_DeleteBySourceID_Call {
	return &MockKnowledgeRepository_DeleteBySourceID_Call{Call: _e.mock.On("DeleteBySourceID", ctx, sourceID)}
}

func (_c *MockKnowledgeRepository_DeleteBySourceID_Call) Run(run func(ctx context.Context, sourceID uuid.UUID)) *MockKnowledgeRepository_DeleteBySourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_DeleteBySourceID_Call) Return(err error) *MockKnowledgeRepository_DeleteBySourceID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKnowledgeRepository_DeleteBySourceID_Call) RunAndReturn(run func(ctx context.Context, sourceID uuid.UUID) error) *MockKnowledgeRepository_DeleteBySourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockKnowledgeRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKnowledgeRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockKnowledgeRepository_Exists_Call {
	return &MockKnowledgeRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockKnowledgeRepository_Exists_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKnowledgeRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_Exists_Call) Return(b bool, err error) *MockKnowledgeRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockKnowledgeRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockKnowledgeRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) FindAll(ctx context.Context, limit int, offset int) ([]*entities.Knowledge, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Knowledge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*entities.Knowledge, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*entities.Knowledge); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Knowledge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockKnowledgeRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockKnowledgeRepository_Expecter) FindAll(ctx interface{}, limit interface{}, offset interface{}) *MockKnowledgeRepository_FindAll_Call {
	return &MockKnowledgeRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, limit, offset)}
}

func (_c *MockKnowledgeRepository_FindAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockKnowledgeRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_FindAll_Call) Return(knowledges []*entities.Knowledge, err error) *MockKnowledgeRepository_FindAll_Call {
	_c.Call.Return(knowledges, err)
	return _c
}

func (_c *MockKnowledgeRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*entities.Knowledge, error)) *MockKnowledgeRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.Knowledge, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Knowledge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Knowledge, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Knowledge); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Knowledge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockKnowledgeRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockKnowledgeRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockKnowledgeRepository_FindByID_Call {
	return &MockKnowledgeRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockKnowledgeRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockKnowledgeRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_FindByID_Call) Return(knowledge *entities.Knowledge, err error) *MockKnowledgeRepository_FindByID_Call {
	_c.Call.Return(knowledge, err)
	return _c
}

func (_c *MockKnowledgeRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Knowledge, error)) *MockKnowledgeRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) FindByIDs(ctx context.Context, ids []uuid.UUID) ([]*entities.Knowledge, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*entities.Knowledge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*entities.Knowledge, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*entities.Knowledge); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Knowledge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockKnowledgeRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockKnowledgeRepository_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockKnowledgeRepository_FindByIDs_Call {
	return &MockKnowledgeRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockKnowledgeRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockKnowledgeRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_FindByIDs_Call) Return(knowledges []*entities.Knowledge, err error) *MockKnowledgeRepository_FindByIDs_Call {
	_c.Call.Return(knowledges, err)
	return _c
}

func (_c *MockKnowledgeRepository_FindByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) ([]*entities.Knowledge, error)) *MockKnowledgeRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySourceID provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) GetBySourceID(ctx context.Context, sourceID uuid.UUID) ([]*entities.Knowledge, error) {
	ret := _mock.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySourceID")
	}

	var r0 []*entities.Knowledge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.Knowledge, error)); ok {
		return returnFunc(ctx, sourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.Knowledge); ok {
		r0 = returnFunc(ctx, sourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Knowledge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKnowledgeRepository_GetBySourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySourceID'
type MockKnowledgeRepository_GetBySourceID_Call struct {
	*mock.Call
}

// GetBySourceID is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID uuid.UUID
func (_e *MockKnowledgeRepository_Expecter) GetBySourceID(ctx interface{}, sourceID interface{}) *MockKnowledgeRepository_GetBySourceID_Call {
	return &MockKnowledgeRepository_GetBySourceID_Call{Call: _e.mock.On("GetBySourceID", ctx, sourceID)}
}

func (_c *MockKnowledgeRepository_GetBySourceID_Call) Run(run func(ctx context.Context, sourceID uuid.UUID)) *MockKnowledgeRepository_GetBySourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_GetBySourceID_Call) Return(knowledges []*entities.Knowledge, err error) *MockKnowledgeRepository_GetBySourceID_Call {
	_c.Call.Return(knowledges, err)
	return _c
}

func (_c *MockKnowledgeRepository_GetBySourceID_Call) RunAndReturn(run func(ctx context.Context, sourceID uuid.UUID) ([]*entities.Knowledge, error)) *MockKnowledgeRepository_GetBySourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) Save(ctx context.Context, knowledge *entities.Knowledge) error {
	ret := _mock.Called(ctx, knowledge)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Knowledge) error); ok {
		r0 = returnFunc(ctx, knowledge)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKnowledgeRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockKnowledgeRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledge *entities.Knowledge
func (_e *MockKnowledgeRepository_Expecter) Save(ctx interface{}, knowledge interface{}) *MockKnowledgeRepository_Save_Call {
	return &MockKnowledgeRepository_Save_Call{Call: _e.mock.On("Save", ctx, knowledge)}
}

func (_c *MockKnowledgeRepository_Save_Call) Run(run func(ctx context.Context, knowledge *entities.Knowledge)) *MockKnowledgeRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Knowledge
		if args[1] != nil {
			arg1 = args[1].(*entities.Knowledge)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_Save_Call) Return(err error) *MockKnowledgeRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKnowledgeRepository_Save_Call) RunAndReturn(run func(ctx context.Context, knowledge *entities.Knowledge) error) *MockKnowledgeRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function for the type MockKnowledgeRepository
func (_mock *MockKnowledgeRepository) SaveBatch(ctx context.Context, knowledges []*entities.Knowledge) error {
	ret := _mock.Called(ctx, knowledges)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.Knowledge) error); ok {
		r0 = returnFunc(ctx, knowledges)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKnowledgeRepository_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type MockKnowledgeRepository_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledges []*entities.Knowledge
func (_e *MockKnowledgeRepository_Expecter) SaveBatch(ctx interface{}, knowledges interface{}) *MockKnowledgeRepository_SaveBatch_Call {
	return &MockKnowledgeRepository_SaveBatch_Call{Call: _e.mock.On("SaveBatch", ctx, knowledges)}
}

func (_c *MockKnowledgeRepository_SaveBatch_Call) Run(run func(ctx context.Context, knowledges []*entities.Knowledge)) *MockKnowledgeRepository_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.Knowledge
		if args[1] != nil {
			arg1 = args[1].([]*entities.Knowledge)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKnowledgeRepository_SaveBatch_Call) Return(err error) *MockKnowledgeRepository_SaveBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKnowledgeRepository_SaveBatch_Call) RunAndReturn(run func(ctx context.Context, knowledges []*entities.Knowledge) error) *MockKnowledgeRepository_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}
