// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/pkg/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotebookRepository creates a new instance of MockNotebookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotebookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotebookRepository {
	mock := &MockNotebookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotebookRepository is an autogenerated mock type for the NotebookRepository type
type MockNotebookRepository struct {
	mock.Mock
}

type MockNotebookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotebookRepository) EXPECT() *MockNotebookRepository_Expecter {
	return &MockNotebookRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotebookRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockNotebookRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNotebookRepository_Expecter) Count(ctx interface{}) *MockNotebookRepository_Count_Call {
	return &MockNotebookRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockNotebookRepository_Count_Call) Run(run func(ctx context.Context)) *MockNotebookRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_Count_Call) Return(n int64, err error) *MockNotebookRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotebookRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockNotebookRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotebookRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotebookRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotebookRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockNotebookRepository_Delete_Call {
	return &MockNotebookRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockNotebookRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotebookRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_Delete_Call) Return(err error) *MockNotebookRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotebookRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockNotebookRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotebookRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockNotebookRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotebookRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockNotebookRepository_Exists_Call {
	return &MockNotebookRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockNotebookRepository_Exists_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotebookRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_Exists_Call) Return(b bool, err error) *MockNotebookRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockNotebookRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockNotebookRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) FindAll(ctx context.Context, limit int, offset int) ([]*entities.Notebook, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Notebook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*entities.Notebook, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*entities.Notebook); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Notebook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotebookRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockNotebookRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockNotebookRepository_Expecter) FindAll(ctx interface{}, limit interface{}, offset interface{}) *MockNotebookRepository_FindAll_Call {
	return &MockNotebookRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, limit, offset)}
}

func (_c *MockNotebookRepository_FindAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockNotebookRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_FindAll_Call) Return(notebooks []*entities.Notebook, err error) *MockNotebookRepository_FindAll_Call {
	_c.Call.Return(notebooks, err)
	return _c
}

func (_c *MockNotebookRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*entities.Notebook, error)) *MockNotebookRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.Notebook, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Notebook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Notebook, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Notebook); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Notebook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotebookRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockNotebookRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNotebookRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockNotebookRepository_FindByID_Call {
	return &MockNotebookRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockNotebookRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNotebookRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_FindByID_Call) Return(notebook *entities.Notebook, err error) *MockNotebookRepository_FindByID_Call {
	_c.Call.Return(notebook, err)
	return _c
}

func (_c *MockNotebookRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Notebook, error)) *MockNotebookRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStatus provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) FindByStatus(ctx context.Context, status string, limit int, offset int) ([]*entities.Notebook, error) {
	ret := _mock.Called(ctx, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []*entities.Notebook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entities.Notebook, error)); ok {
		return returnFunc(ctx, status, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*entities.Notebook); ok {
		r0 = returnFunc(ctx, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Notebook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotebookRepository_FindByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStatus'
type MockNotebookRepository_FindByStatus_Call struct {
	*mock.Call
}

// FindByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - limit int
//   - offset int
func (_e *MockNotebookRepository_Expecter) FindByStatus(ctx interface{}, status interface{}, limit interface{}, offset interface{}) *MockNotebookRepository_FindByStatus_Call {
	return &MockNotebookRepository_FindByStatus_Call{Call: _e.mock.On("FindByStatus", ctx, status, limit, offset)}
}

func (_c *MockNotebookRepository_FindByStatus_Call) Run(run func(ctx context.Context, status string, limit int, offset int)) *MockNotebookRepository_FindByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_FindByStatus_Call) Return(notebooks []*entities.Notebook, err error) *MockNotebookRepository_FindByStatus_Call {
	_c.Call.Return(notebooks, err)
	return _c
}

func (_c *MockNotebookRepository_FindByStatus_Call) RunAndReturn(run func(ctx context.Context, status string, limit int, offset int) ([]*entities.Notebook, error)) *MockNotebookRepository_FindByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTags provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) FindByTags(ctx context.Context, tags []string, limit int, offset int) ([]*entities.Notebook, error) {
	ret := _mock.Called(ctx, tags, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByTags")
	}

	var r0 []*entities.Notebook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int, int) ([]*entities.Notebook, error)); ok {
		return returnFunc(ctx, tags, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int, int) []*entities.Notebook); ok {
		r0 = returnFunc(ctx, tags, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Notebook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, int, int) error); ok {
		r1 = returnFunc(ctx, tags, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotebookRepository_FindByTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTags'
type MockNotebookRepository_FindByTags_Call struct {
	*mock.Call
}

// FindByTags is a helper method to define mock.On call
//   - ctx context.Context
//   - tags []string
//   - limit int
//   - offset int
func (_e *MockNotebookRepository_Expecter) FindByTags(ctx interface{}, tags interface{}, limit interface{}, offset interface{}) *MockNotebookRepository_FindByTags_Call {
	return &MockNotebookRepository_FindByTags_Call{Call: _e.mock.On("FindByTags", ctx, tags, limit, offset)}
}

func (_c *MockNotebookRepository_FindByTags_Call) Run(run func(ctx context.Context, tags []string, limit int, offset int)) *MockNotebookRepository_FindByTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_FindByTags_Call) Return(notebooks []*entities.Notebook, err error) *MockNotebookRepository_FindByTags_Call {
	_c.Call.Return(notebooks, err)
	return _c
}

func (_c *MockNotebookRepository_FindByTags_Call) RunAndReturn(run func(ctx context.Context, tags []string, limit int, offset int) ([]*entities.Notebook, error)) *MockNotebookRepository_FindByTags_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) Save(ctx context.Context, notebook *entities.Notebook) error {
	ret := _mock.Called(ctx, notebook)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Notebook) error); ok {
		r0 = returnFunc(ctx, notebook)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotebookRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockNotebookRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - notebook *entities.Notebook
func (_e *MockNotebookRepository_Expecter) Save(ctx interface{}, notebook interface{}) *MockNotebookRepository_Save_Call {
	return &MockNotebookRepository_Save_Call{Call: _e.mock.On("Save", ctx, notebook)}
}

func (_c *MockNotebookRepository_Save_Call) Run(run func(ctx context.Context, notebook *entities.Notebook)) *MockNotebookRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Notebook
		if args[1] != nil {
			arg1 = args[1].(*entities.Notebook)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_Save_Call) Return(err error) *MockNotebookRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotebookRepository_Save_Call) RunAndReturn(run func(ctx context.Context, notebook *entities.Notebook) error) *MockNotebookRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockNotebookRepository
func (_mock *MockNotebookRepository) Search(ctx context.Context, query string, limit int, offset int) ([]*entities.Notebook, error) {
	ret := _mock.Called(ctx, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entities.Notebook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entities.Notebook, error)); ok {
		return returnFunc(ctx, query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*entities.Notebook); ok {
		r0 = returnFunc(ctx, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Notebook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotebookRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockNotebookRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
//   - offset int
func (_e *MockNotebookRepository_Expecter) Search(ctx interface{}, query interface{}, limit interface{}, offset interface{}) *MockNotebookRepository_Search_Call {
	return &MockNotebookRepository_Search_Call{Call: _e.mock.On("Search", ctx, query, limit, offset)}
}

func (_c *MockNotebookRepository_Search_Call) Run(run func(ctx context.Context, query string, limit int, offset int)) *MockNotebookRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotebookRepository_Search_Call) Return(notebooks []*entities.Notebook, err error) *MockNotebookRepository_Search_Call {
	_c.Call.Return(notebooks, err)
	return _c
}

func (_c *MockNotebookRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query string, limit int, offset int) ([]*entities.Notebook, error)) *MockNotebookRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}
