// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/pkg/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSentenceRepository creates a new instance of MockSentenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSentenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSentenceRepository {
	mock := &MockSentenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSentenceRepository is an autogenerated mock type for the SentenceRepository type
type MockSentenceRepository struct {
	mock.Mock
}

type MockSentenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSentenceRepository) EXPECT() *MockSentenceRepository_Expecter {
	return &MockSentenceRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSentenceRepository
func (_mock *MockSentenceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSentenceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSentenceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSentenceRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSentenceRepository_Delete_Call {
	return &MockSentenceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSentenceRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSentenceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSentenceRepository_Delete_Call) Return(err error) *MockSentenceRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSentenceRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSentenceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByKnowledgeID provides a mock function for the type MockSentenceRepository
func (_mock *MockSentenceRepository) DeleteByKnowledgeID(ctx context.Context, knowledgeID uuid.UUID) error {
	ret := _mock.Called(ctx, knowledgeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByKnowledgeID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, knowledgeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSentenceRepository_DeleteByKnowledgeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByKnowledgeID'
type MockSentenceRepository_DeleteByKnowledgeID_Call struct {
	*mock.Call
}

// DeleteByKnowledgeID is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID uuid.UUID
func (_e *MockSentenceRepository_Expecter) DeleteByKnowledgeID(ctx interface{}, knowledgeID interface{}) *MockSentenceRepository_DeleteByKnowledgeID_Call {
	return &MockSentenceRepository_DeleteByKnowledgeID_Call{Call: _e.mock.On("DeleteByKnowledgeID", ctx, knowledgeID)}
}

func (_c *MockSentenceRepository_DeleteByKnowledgeID_Call) Run(run func(ctx context.Context, knowledgeID uuid.UUID)) *MockSentenceRepository_DeleteByKnowledgeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSentenceRepository_DeleteByKnowledgeID_Call) Return(err error) *MockSentenceRepository_DeleteByKnowledgeID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSentenceRepository_DeleteByKnowledgeID_Call) RunAndReturn(run func(ctx context.Context, knowledgeID uuid.UUID) error) *MockSentenceRepository_DeleteByKnowledgeID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySourceID provides a mock function for the type MockSentenceRepository
func (_mock *MockSentenceRepository) DeleteBySourceID(ctx context.Context, sourceID uuid.UUID) error {
	ret := _mock.Called(ctx, sourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySourceID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sourceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSentenceRepository_DeleteBySourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySourceID'
type MockSentenceRepository_DeleteBySourceID_Call struct {
	*mock.Call
}

// DeleteBySourceID is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceID uuid.UUID
func (_e *MockSentenceRepository_Expecter) DeleteBySourceID(ctx interface{}, sourceID interface{}) *MockSentenceRepository_DeleteBySourceID_Call {
	return &MockSentenceRepository_DeleteBySourceID_Call{Call: _e.mock.On("DeleteBySourceID", ctx, sourceID)}
}

func (_c *MockSentenceRepository_DeleteBySourceID_Call) Run(run func(ctx context.Context, sourceID uuid.UUID)) *MockSentenceRepository_DeleteBySourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSentenceRepository_DeleteBySourceID_Call) Return(err error) *MockSentenceRepository_DeleteBySourceID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSentenceRepository_DeleteBySourceID_Call) RunAndReturn(run func(ctx context.Context, sourceID uuid.UUID) error) *MockSentenceRepository_DeleteBySourceID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockSentenceRepository
func (_mock *MockSentenceRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.Sentence, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Sentence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Sentence, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Sentence); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Sentence)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSentenceRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSentenceRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSentenceRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockSentenceRepository_FindByID_Call {
	return &MockSentenceRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSentenceRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSentenceRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSentenceRepository_FindByID_Call) Return(sentence *entities.Sentence, err error) *MockSentenceRepository_FindByID_Call {
	_c.Call.Return(sentence, err)
	return _c
}

func (_c *MockSentenceRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Sentence, error)) *MockSentenceRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByKnowledgeID provides a mock function for the type MockSentenceRepository
func (_mock *MockSentenceRepository) FindByKnowledgeID(ctx context.Context, knowledgeID uuid.UUID) ([]*entities.Sentence, error) {
	ret := _mock.Called(ctx, knowledgeID)

	if len(ret) == 0 {
		panic("no return value specified for FindByKnowledgeID")
	}

	var r0 []*entities.Sentence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.Sentence, error)); ok {
		return returnFunc(ctx, knowledgeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.Sentence); ok {
		r0 = returnFunc(ctx, knowledgeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Sentence)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, knowledgeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSentenceRepository_FindByKnowledgeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByKnowledgeID'
type MockSentenceRepository_FindByKnowledgeID_Call struct {
	*mock.Call
}

// FindByKnowledgeID is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID uuid.UUID
func (_e *MockSentenceRepository_Expecter) FindByKnowledgeID(ctx interface{}, knowledgeID interface{}) *MockSentenceRepository_FindByKnowledgeID_Call {
	return &MockSentenceRepository_FindByKnowledgeID_Call{Call: _e.mock.On("FindByKnowledgeID", ctx, knowledgeID)}
}

func (_c *MockSentenceRepository_FindByKnowledgeID_Call) Run(run func(ctx context.Context, knowledgeID uuid.UUID)) *MockSentenceRepository_FindByKnowledgeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSentenceRepository_FindByKnowledgeID_Call) Return(sentences []*entities.Sentence, err error) *MockSentenceRepository_FindByKnowledgeID_Call {
	_c.Call.Return(sentences, err)
	return _c
}

func (_c *MockSentenceRepository_FindByKnowledgeID_Call) RunAndReturn(run func(ctx context.Context, knowledgeID uuid.UUID) ([]*entities.Sentence, error)) *MockSentenceRepository_FindByKnowledgeID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSentenceRepository
func (_mock *MockSentenceRepository) Save(ctx context.Context, sentence *entities.Sentence) error {
	ret := _mock.Called(ctx, sentence)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Sentence) error); ok {
		r0 = returnFunc(ctx, sentence)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSentenceRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSentenceRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - sentence *entities.Sentence
func (_e *MockSentenceRepository_Expecter) Save(ctx interface{}, sentence interface{}) *MockSentenceRepository_Save_Call {
	return &MockSentenceRepository_Save_Call{Call: _e.mock.On("Save", ctx, sentence)}
}

func (_c *MockSentenceRepository_Save_Call) Run(run func(ctx context.Context, sentence *entities.Sentence)) *MockSentenceRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Sentence
		if args[1] != nil {
			arg1 = args[1].(*entities.Sentence)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSentenceRepository_Save_Call) Return(err error) *MockSentenceRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSentenceRepository_Save_Call) RunAndReturn(run func(ctx context.Context, sentence *entities.Sentence) error) *MockSentenceRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function for the type MockSentenceRepository
func (_mock *MockSentenceRepository) SaveBatch(ctx context.Context, sentences []*entities.Sentence) error {
	ret := _mock.Called(ctx, sentences)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.Sentence) error); ok {
		r0 = returnFunc(ctx, sentences)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSentenceRepository_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type MockSentenceRepository_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - sentences []*entities.Sentence
func (_e *MockSentenceRepository_Expecter) SaveBatch(ctx interface{}, sentences interface{}) *MockSentenceRepository_SaveBatch_Call {
	return &MockSentenceRepository_SaveBatch_Call{Call: _e.mock.On("SaveBatch", ctx, sentences)}
}

func (_c *MockSentenceRepository_SaveBatch_Call) Run(run func(ctx context.Context, sentences []*entities.Sentence)) *MockSentenceRepository_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.Sentence
		if args[1] != nil {
			arg1 = args[1].([]*entities.Sentence)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSentenceRepository_SaveBatch_Call) Return(err error) *MockSentenceRepository_SaveBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSentenceRepository_SaveBatch_Call) RunAndReturn(run func(ctx context.Context, sentences []*entities.Sentence) error) *MockSentenceRepository_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}
