// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/oniharnantyo/eino-notebook/internal/core/domain/entities"
	"github.com/oniharnantyo/eino-notebook/internal/core/domain/repositories"
	"github.com/oniharnantyo/eino-notebook/pkg/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSourceRepository creates a new instance of MockSourceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceRepository {
	mock := &MockSourceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSourceRepository is an autogenerated mock type for the SourceRepository type
type MockSourceRepository struct {
	mock.Mock
}

type MockSourceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceRepository) EXPECT() *MockSourceRepository_Expecter {
	return &MockSourceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) Create(ctx context.Context, source *entities.Source) error {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Source) error); ok {
		r0 = returnFunc(ctx, source)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSourceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - source *entities.Source
func (_e *MockSourceRepository_Expecter) Create(ctx interface{}, source interface{}) *MockSourceRepository_Create_Call {
	return &MockSourceRepository_Create_Call{Call: _e.mock.On("Create", ctx, source)}
}

func (_c *MockSourceRepository_Create_Call) Run(run func(ctx context.Context, source *entities.Source)) *MockSourceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Source
		if args[1] != nil {
			arg1 = args[1].(*entities.Source)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_Create_Call) Return(err error) *MockSourceRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceRepository_Create_Call) RunAndReturn(run func(ctx context.Context, source *entities.Source) error) *MockSourceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSourceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSourceRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSourceRepository_Delete_Call {
	return &MockSourceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSourceRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSourceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_Delete_Call) Return(err error) *MockSourceRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSourceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.Source, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Source, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Source); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Source)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSourceRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSourceRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSourceRepository_GetByID_Call {
	return &MockSourceRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSourceRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSourceRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_GetByID_Call) Return(source *entities.Source, err error) *MockSourceRepository_GetByID_Call {
	_c.Call.Return(source, err)
	return _c
}

func (_c *MockSourceRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entities.Source, error)) *MockSourceRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNotebookID provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) GetByNotebookID(ctx context.Context, notebookID uuid.UUID) ([]*entities.Source, error) {
	ret := _mock.Called(ctx, notebookID)

	if len(ret) == 0 {
		panic("no return value specified for GetByNotebookID")
	}

	var r0 []*entities.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entities.Source, error)); ok {
		return returnFunc(ctx, notebookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entities.Source); ok {
		r0 = returnFunc(ctx, notebookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Source)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, notebookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceRepository_GetByNotebookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNotebookID'
type MockSourceRepository_GetByNotebookID_Call struct {
	*mock.Call
}

// GetByNotebookID is a helper method to define mock.On call
//   - ctx context.Context
//   - notebookID uuid.UUID
func (_e *MockSourceRepository_Expecter) GetByNotebookID(ctx interface{}, notebookID interface{}) *MockSourceRepository_GetByNotebookID_Call {
	return &MockSourceRepository_GetByNotebookID_Call{Call: _e.mock.On("GetByNotebookID", ctx, notebookID)}
}

func (_c *MockSourceRepository_GetByNotebookID_Call) Run(run func(ctx context.Context, notebookID uuid.UUID)) *MockSourceRepository_GetByNotebookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_GetByNotebookID_Call) Return(sources []*entities.Source, err error) *MockSourceRepository_GetByNotebookID_Call {
	_c.Call.Return(sources, err)
	return _c
}

func (_c *MockSourceRepository_GetByNotebookID_Call) RunAndReturn(run func(ctx context.Context, notebookID uuid.UUID) ([]*entities.Source, error)) *MockSourceRepository_GetByNotebookID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByURI provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) GetByURI(ctx context.Context, notebookID uuid.UUID, uri string) (*entities.Source, error) {
	ret := _mock.Called(ctx, notebookID, uri)

	if len(ret) == 0 {
		panic("no return value specified for GetByURI")
	}

	var r0 *entities.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entities.Source, error)); ok {
		return returnFunc(ctx, notebookID, uri)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entities.Source); ok {
		r0 = returnFunc(ctx, notebookID, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Source)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, notebookID, uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceRepository_GetByURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByURI'
type MockSourceRepository_GetByURI_Call struct {
	*mock.Call
}

// GetByURI is a helper method to define mock.On call
//   - ctx context.Context
//   - notebookID uuid.UUID
//   - uri string
func (_e *MockSourceRepository_Expecter) GetByURI(ctx interface{}, notebookID interface{}, uri interface{}) *MockSourceRepository_GetByURI_Call {
	return &MockSourceRepository_GetByURI_Call{Call: _e.mock.On("GetByURI", ctx, notebookID, uri)}
}

func (_c *MockSourceRepository_GetByURI_Call) Run(run func(ctx context.Context, notebookID uuid.UUID, uri string)) *MockSourceRepository_GetByURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSourceRepository_GetByURI_Call) Return(source *entities.Source, err error) *MockSourceRepository_GetByURI_Call {
	_c.Call.Return(source, err)
	return _c
}

func (_c *MockSourceRepository_GetByURI_Call) RunAndReturn(run func(ctx context.Context, notebookID uuid.UUID, uri string) (*entities.Source, error)) *MockSourceRepository_GetByURI_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementChunkCount provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) IncrementChunkCount(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementChunkCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceRepository_IncrementChunkCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementChunkCount'
type MockSourceRepository_IncrementChunkCount_Call struct {
	*mock.Call
}

// IncrementChunkCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSourceRepository_Expecter) IncrementChunkCount(ctx interface{}, id interface{}) *MockSourceRepository_IncrementChunkCount_Call {
	return &MockSourceRepository_IncrementChunkCount_Call{Call: _e.mock.On("IncrementChunkCount", ctx, id)}
}

func (_c *MockSourceRepository_IncrementChunkCount_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSourceRepository_IncrementChunkCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_IncrementChunkCount_Call) Return(err error) *MockSourceRepository_IncrementChunkCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceRepository_IncrementChunkCount_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSourceRepository_IncrementChunkCount_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) List(ctx context.Context, filter repositories.SourceFilter) ([]*entities.Source, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Source
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.SourceFilter) ([]*entities.Source, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.SourceFilter) []*entities.Source); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Source)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.SourceFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, repositories.SourceFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSourceRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSourceRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repositories.SourceFilter
func (_e *MockSourceRepository_Expecter) List(ctx interface{}, filter interface{}) *MockSourceRepository_List_Call {
	return &MockSourceRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockSourceRepository_List_Call) Run(run func(ctx context.Context, filter repositories.SourceFilter)) *MockSourceRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.SourceFilter
		if args[1] != nil {
			arg1 = args[1].(repositories.SourceFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_List_Call) Return(sources []*entities.Source, n int, err error) *MockSourceRepository_List_Call {
	_c.Call.Return(sources, n, err)
	return _c
}

func (_c *MockSourceRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter repositories.SourceFilter) ([]*entities.Source, int, error)) *MockSourceRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListSourceSummariesByID provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) ListSourceSummariesByID(ctx context.Context, ids []uuid.UUID) ([]*entities.Source, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListSourceSummariesByID")
	}

	var r0 []*entities.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*entities.Source, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*entities.Source); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Source)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceRepository_ListSourceSummariesByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSourceSummariesByID'
type MockSourceRepository_ListSourceSummariesByID_Call struct {
	*mock.Call
}

// ListSourceSummariesByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockSourceRepository_Expecter) ListSourceSummariesByID(ctx interface{}, ids interface{}) *MockSourceRepository_ListSourceSummariesByID_Call {
	return &MockSourceRepository_ListSourceSummariesByID_Call{Call: _e.mock.On("ListSourceSummariesByID", ctx, ids)}
}

func (_c *MockSourceRepository_ListSourceSummariesByID_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockSourceRepository_ListSourceSummariesByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_ListSourceSummariesByID_Call) Return(sources []*entities.Source, err error) *MockSourceRepository_ListSourceSummariesByID_Call {
	_c.Call.Return(sources, err)
	return _c
}

func (_c *MockSourceRepository_ListSourceSummariesByID_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) ([]*entities.Source, error)) *MockSourceRepository_ListSourceSummariesByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSourceRepository
func (_mock *MockSourceRepository) Update(ctx context.Context, source *entities.Source) error {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Source) error); ok {
		r0 = returnFunc(ctx, source)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSourceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - source *entities.Source
func (_e *MockSourceRepository_Expecter) Update(ctx interface{}, source interface{}) *MockSourceRepository_Update_Call {
	return &MockSourceRepository_Update_Call{Call: _e.mock.On("Update", ctx, source)}
}

func (_c *MockSourceRepository_Update_Call) Run(run func(ctx context.Context, source *entities.Source)) *MockSourceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Source
		if args[1] != nil {
			arg1 = args[1].(*entities.Source)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceRepository_Update_Call) Return(err error) *MockSourceRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceRepository_Update_Call) RunAndReturn(run func(ctx context.Context, source *entities.Source) error) *MockSourceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
